2013-12-19 07:03:10.682 [error] <0.155.0> gen_server list terminated with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52
2013-12-19 07:03:10.683 [error] <0.155.0> CRASH REPORT Process list with 0 neighbours exited with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52 in gen_server:terminate/6 line 744
2013-12-19 07:03:10.684 [error] <0.154.0> Supervisor {<0.154.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.153.0>) at <0.155.0> exit with reason no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52 in context child_terminated
2014-01-02 22:18:48.931 [error] <0.122.0> gen_server list terminated with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52
2014-01-02 22:18:48.932 [error] <0.122.0> CRASH REPORT Process list with 0 neighbours exited with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52 in gen_server:terminate/6 line 744
2014-01-02 22:18:48.932 [error] <0.121.0> Supervisor {<0.121.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at <0.122.0> exit with reason no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52 in context child_terminated
2014-01-02 22:19:02.644 [error] <0.142.0> gen_server list terminated with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52
2014-01-02 22:19:02.645 [error] <0.142.0> CRASH REPORT Process list with 0 neighbours exited with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52 in gen_server:terminate/6 line 744
2014-01-02 22:19:02.645 [error] <0.121.0> Supervisor {<0.121.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at <0.142.0> exit with reason no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52 in context child_terminated
2014-01-02 22:19:31.297 [error] <0.119.0> Supervisor {<0.119.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListData' started with 'Elixir.ListData':start_link() at <0.120.0> exit with reason killed in context child_terminated
2014-01-02 22:19:52.210 [error] <0.119.0> Supervisor {<0.119.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListData' started with 'Elixir.ListData':start_link() at <0.153.0> exit with reason killed in context child_terminated
2014-01-02 22:20:16.566 [error] <0.121.0> Supervisor {<0.121.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at <0.146.0> exit with reason killed in context child_terminated
2014-01-02 22:20:16.567 [error] <0.121.0> Supervisor {<0.121.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at <0.146.0> exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.568 [error] <0.164.0> CRASH REPORT Process <0.164.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.568 [error] <0.166.0> CRASH REPORT Process <0.166.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.569 [error] <0.121.0> Supervisor {<0.121.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at {restarting,<0.146.0>} exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.569 [error] <0.168.0> CRASH REPORT Process <0.168.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.570 [error] <0.121.0> Supervisor {<0.121.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at {restarting,<0.146.0>} exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.570 [error] <0.170.0> CRASH REPORT Process <0.170.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.571 [error] <0.121.0> Supervisor {<0.121.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at {restarting,<0.146.0>} exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.571 [error] <0.172.0> CRASH REPORT Process <0.172.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.572 [error] <0.121.0> Supervisor {<0.121.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at {restarting,<0.146.0>} exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.572 [error] <0.121.0> Supervisor {<0.121.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at {restarting,<0.146.0>} exit with reason reached_max_restart_intensity in context shutdown
2014-01-02 22:20:16.572 [error] <0.119.0> Supervisor {<0.119.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.120.0>) at <0.121.0> exit with reason shutdown in context child_terminated
2014-01-02 22:20:16.572 [error] <0.175.0> CRASH REPORT Process <0.175.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.572 [error] <0.174.0> Supervisor {<0.174.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.572 [error] <0.119.0> Supervisor {<0.119.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.120.0>) at <0.121.0> exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.120.0>,get_state]}}}} in context start_error
2014-01-02 22:20:16.572 [error] <0.178.0> CRASH REPORT Process <0.178.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.572 [error] <0.177.0> Supervisor {<0.177.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.573 [error] <0.119.0> Supervisor {<0.119.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.120.0>) at {restarting,<0.121.0>} exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.120.0>,get_state]}}}} in context start_error
2014-01-02 22:20:16.573 [error] <0.180.0> Supervisor {<0.180.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.573 [error] <0.181.0> CRASH REPORT Process <0.181.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.573 [error] <0.119.0> Supervisor {<0.119.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.120.0>) at {restarting,<0.121.0>} exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.120.0>,get_state]}}}} in context start_error
2014-01-02 22:20:16.573 [error] <0.184.0> CRASH REPORT Process <0.184.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.573 [error] <0.183.0> Supervisor {<0.183.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.573 [error] <0.119.0> Supervisor {<0.119.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.120.0>) at {restarting,<0.121.0>} exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.120.0>,get_state]}}}} in context start_error
2014-01-02 22:20:16.574 [error] <0.187.0> CRASH REPORT Process <0.187.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.120.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:16.574 [error] <0.186.0> Supervisor {<0.186.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.120.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.120.0>, get_state) in context start_error
2014-01-02 22:20:16.574 [error] <0.119.0> Supervisor {<0.119.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.120.0>) at {restarting,<0.121.0>} exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.120.0>,get_state]}}}} in context start_error
2014-01-02 22:20:16.574 [error] <0.119.0> Supervisor {<0.119.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.120.0>) at {restarting,<0.121.0>} exit with reason reached_max_restart_intensity in context shutdown
2014-01-02 22:20:16.574 [error] <0.118.0> Supervisor {<0.118.0>,'Elixir.SupervisedListServer.Supervisor'} had child 'Elixir.ListSupervisor' started with 'Elixir.ListSupervisor':start_link() at <0.119.0> exit with reason shutdown in context child_terminated
2014-01-02 22:20:38.046 [error] <0.189.0> Supervisor {<0.189.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListData' started with 'Elixir.ListData':start_link() at <0.190.0> exit with reason killed in context child_terminated
2014-01-02 22:20:46.053 [error] <0.192.0> gen_server list terminated with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52
2014-01-02 22:20:46.053 [error] <0.192.0> CRASH REPORT Process list with 0 neighbours exited with reason: no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52 in gen_server:terminate/6 line 744
2014-01-02 22:20:46.054 [error] <0.191.0> Supervisor {<0.191.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at <0.192.0> exit with reason no match of right hand value 2 in 'Elixir.ListServer':handle_cast/2 line 52 in context child_terminated
2014-01-02 22:20:46.055 [error] <0.201.0> CRASH REPORT Process <0.201.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.055 [error] <0.191.0> Supervisor {<0.191.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at <0.192.0> exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.056 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.056 [error] <0.191.0> Supervisor {<0.191.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at {restarting,<0.192.0>} exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.057 [error] <0.206.0> CRASH REPORT Process <0.206.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.057 [error] <0.191.0> Supervisor {<0.191.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at {restarting,<0.192.0>} exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.057 [error] <0.208.0> CRASH REPORT Process <0.208.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.057 [error] <0.191.0> Supervisor {<0.191.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at {restarting,<0.192.0>} exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.057 [error] <0.210.0> CRASH REPORT Process <0.210.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.057 [error] <0.191.0> Supervisor {<0.191.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at {restarting,<0.192.0>} exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.058 [error] <0.191.0> Supervisor {<0.191.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at {restarting,<0.192.0>} exit with reason reached_max_restart_intensity in context shutdown
2014-01-02 22:20:46.059 [error] <0.189.0> Supervisor {<0.189.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.190.0>) at <0.191.0> exit with reason shutdown in context child_terminated
2014-01-02 22:20:46.059 [error] <0.213.0> CRASH REPORT Process <0.213.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.060 [error] <0.212.0> Supervisor {<0.212.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.060 [error] <0.189.0> Supervisor {<0.189.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.190.0>) at <0.191.0> exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.190.0>,get_state]}}}} in context start_error
2014-01-02 22:20:46.060 [error] <0.216.0> CRASH REPORT Process <0.216.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.061 [error] <0.215.0> Supervisor {<0.215.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.062 [error] <0.189.0> Supervisor {<0.189.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.190.0>) at {restarting,<0.191.0>} exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.190.0>,get_state]}}}} in context start_error
2014-01-02 22:20:46.062 [error] <0.219.0> CRASH REPORT Process <0.219.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.062 [error] <0.218.0> Supervisor {<0.218.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.063 [error] <0.189.0> Supervisor {<0.189.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.190.0>) at {restarting,<0.191.0>} exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.190.0>,get_state]}}}} in context start_error
2014-01-02 22:20:46.063 [error] <0.222.0> CRASH REPORT Process <0.222.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.063 [error] <0.221.0> Supervisor {<0.221.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.063 [error] <0.189.0> Supervisor {<0.189.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.190.0>) at {restarting,<0.191.0>} exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.190.0>,get_state]}}}} in context start_error
2014-01-02 22:20:46.063 [error] <0.225.0> CRASH REPORT Process <0.225.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.190.0>, get_state) in gen_server:init_it/6 line 328
2014-01-02 22:20:46.063 [error] <0.224.0> Supervisor {<0.224.0>,'Elixir.ListSubSupervisor'} had child 'Elixir.ListServer' started with 'Elixir.ListServer':start_link(<0.190.0>) at undefined exit with reason no such process or port in call to gen_server:call(<0.190.0>, get_state) in context start_error
2014-01-02 22:20:46.063 [error] <0.189.0> Supervisor {<0.189.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.190.0>) at {restarting,<0.191.0>} exit with reason {shutdown,{failed_to_start_child,'Elixir.ListServer',{noproc,{gen_server,call,[<0.190.0>,get_state]}}}} in context start_error
2014-01-02 22:20:46.064 [error] <0.189.0> Supervisor {<0.189.0>,'Elixir.ListSupervisor'} had child 'Elixir.ListSubSupervisor' started with 'Elixir.ListSubSupervisor':start_link(<0.190.0>) at {restarting,<0.191.0>} exit with reason reached_max_restart_intensity in context shutdown
2014-01-02 22:20:46.064 [error] <0.118.0> Supervisor {<0.118.0>,'Elixir.SupervisedListServer.Supervisor'} had child 'Elixir.ListSupervisor' started with 'Elixir.ListSupervisor':start_link() at <0.189.0> exit with reason shutdown in context child_terminated
